/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import grafo.Grafo;
import grafo.Lector;
import grafo.Vertice;
import grafo.Producto;
import grafo.Vertice;
import grafo.GraphStream;
import javax.swing.JOptionPane;
import grafo.Lista;


/**
 *
 * @author Liz
 */
public class Menu extends javax.swing.JFrame {
    Grafo matriz = Global.getGrafo();
    /**
     * Creates new form Inicio
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        realizarPedido = new javax.swing.JButton();
        verStock = new javax.swing.JButton();
        gestionarStock = new javax.swing.JButton();
        nuevoAlmacen = new javax.swing.JButton();
        nuevaArista = new javax.swing.JButton();
        verGrafo = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        realizarPedido.setBackground(new java.awt.Color(204, 153, 0));
        realizarPedido.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        realizarPedido.setForeground(new java.awt.Color(51, 51, 51));
        realizarPedido.setText("Realizar Pedido");
        realizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(realizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 160, 40));

        verStock.setBackground(new java.awt.Color(204, 153, 0));
        verStock.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        verStock.setForeground(new java.awt.Color(51, 51, 51));
        verStock.setText("Ver Stock");
        verStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verStockActionPerformed(evt);
            }
        });
        jPanel1.add(verStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 40));

        gestionarStock.setBackground(new java.awt.Color(204, 153, 0));
        gestionarStock.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        gestionarStock.setForeground(new java.awt.Color(51, 51, 51));
        gestionarStock.setText("Gestionar Stock");
        gestionarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarStockActionPerformed(evt);
            }
        });
        jPanel1.add(gestionarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 160, 40));

        nuevoAlmacen.setBackground(new java.awt.Color(204, 153, 0));
        nuevoAlmacen.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        nuevoAlmacen.setForeground(new java.awt.Color(51, 51, 51));
        nuevoAlmacen.setText("Nuevo Almacen");
        nuevoAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 160, 40));

        nuevaArista.setBackground(new java.awt.Color(204, 153, 0));
        nuevaArista.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        nuevaArista.setForeground(new java.awt.Color(51, 51, 51));
        nuevaArista.setText("Nueva Arista");
        nuevaArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAristaActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaArista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 160, 40));

        verGrafo.setBackground(new java.awt.Color(204, 153, 0));
        verGrafo.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        verGrafo.setForeground(new java.awt.Color(51, 51, 51));
        verGrafo.setText("Ver Grafo");
        verGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(verGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 160, 40));

        guardarCambios.setBackground(new java.awt.Color(204, 153, 0));
        guardarCambios.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        guardarCambios.setForeground(new java.awt.Color(51, 51, 51));
        guardarCambios.setText("Guardar Cambios");
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 160, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Headline R", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Seleccione una opcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarPedidoActionPerformed

    private void verStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verStockActionPerformed
        this.setVisible(false);
        ReporteStock stock = new ReporteStock();
    }//GEN-LAST:event_verStockActionPerformed

    private void gestionarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarStockActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        GestionStock stock = new GestionStock();
    }//GEN-LAST:event_gestionarStockActionPerformed

    private void nuevoAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlmacenActionPerformed



        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingresa el nombre del nuevo almacen");
        //si el almacen no existe entonces continua
        if(matriz.searchVertice(nombre) == -1){
            int aristas;
            String arista1;
            int km;
            try{
                if(nombre != null){
                do{
                    aristas = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el numero de aristas(Minimo 2)"));
                }while(aristas < 2);
                    Lista productos = new Lista();
                    matriz.newVertice(nombre, productos);
                    JOptionPane.showMessageDialog(null,"Se va a proceder a guardar los caminos");
                    for (int i = 0; i < aristas; i++) {
                        do{
                            arista1 = JOptionPane.showInputDialog("Ingresa el nombre del almacen correspondiente al camino numero: " + (i+1));
                            System.out.println(matriz.searchVertice(arista1));
                        }while(matriz.searchVertice(arista1) == -1);
                        km = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la cantidad de kilometros(solo numeros) entre los almacenes "+ nombre + " y " + arista1));
                        matriz.newArista(arista1, nombre, km);
                    }
                    JOptionPane.showMessageDialog(null,"Su almacen se ha guardado con exito");
                }

            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error, solo puedes ingresar numeros");
            }
            
            //si el almacen existe termina 
        }else{
            JOptionPane.showMessageDialog(null,"El almacen que ingresaste ya existe");
        }

    }//GEN-LAST:event_nuevoAlmacenActionPerformed

    private void nuevaAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaAristaActionPerformed
        // TODO add your handling code here:
        String almacen1 = JOptionPane.showInputDialog("Ingresa el nombre del primer almacen");
        String almacen2 = JOptionPane.showInputDialog("Ingresa el nombre del segundo almacen");
        if(matriz.searchVertice(almacen1.toUpperCase()) != -1 && matriz.searchVertice(almacen2.toUpperCase()) != -1){
            try{
                int km = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de kilometros entre los almacenes"));
                matriz.newArista(almacen2.toUpperCase(), almacen1.toUpperCase(), km);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error, solo puedes ingresar numeros");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Uno de los almacenes no existe");
        }
    }//GEN-LAST:event_nuevaAristaActionPerformed

    private void verGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGrafoActionPerformed
        // TODO add your handling code here:
        GraphStream graph = new GraphStream();
        Graph graficar = graph.Graphic(Global.getGrafo());
        System.setProperty("org.graphstream.ui", "swing");
        graficar.display();
    }//GEN-LAST:event_verGrafoActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        // TODO add your handling code here:
        Lector lec = new Lector();
        lec.writeTxt(matriz);
    }//GEN-LAST:event_guardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestionarStock;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nuevaArista;
    private javax.swing.JButton nuevoAlmacen;
    private javax.swing.JButton realizarPedido;
    private javax.swing.JButton verGrafo;
    private javax.swing.JButton verStock;
    // End of variables declaration//GEN-END:variables
}
