/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import grafo.Dijkstra;
import grafo.Grafo;
import grafo.Lista;
import grafo.Nodo;
import grafo.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author Liz
 */
public class Pedido extends javax.swing.JFrame {
    Grafo grafo = Global.getGrafo();
    /**
     * Creates new form Inicio
     */
    public Pedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Lista bfs = grafo.BFS(grafo, grafo.getVerts()[0].getName());
        this.panelStock.setText(bfs.printProductos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        numAlmacen = new javax.swing.JTextField();
        vproducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vcantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        camino = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        enviat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelStock = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Headline R", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Realizar Pedido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(51, 51, 51));
        menu.setText("Regresar al menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 160, 20));

        numAlmacen.setBackground(new java.awt.Color(204, 204, 204));
        numAlmacen.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        numAlmacen.setForeground(new java.awt.Color(0, 0, 0));
        numAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(numAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 30, -1));

        vproducto.setBackground(new java.awt.Color(204, 204, 204));
        vproducto.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        vproducto.setForeground(new java.awt.Color(0, 0, 0));
        vproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vproductoActionPerformed(evt);
            }
        });
        jPanel1.add(vproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, -1));

        jLabel5.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Almacen");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Stock");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        jPanel1.add(vcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Producto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        camino.setEditable(false);
        camino.setBackground(new java.awt.Color(204, 204, 204));
        camino.setColumns(20);
        camino.setForeground(new java.awt.Color(0, 0, 0));
        camino.setRows(5);
        jScrollPane1.setViewportView(camino);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 260, 80));

        jLabel8.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cantidad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        enviat.setBackground(new java.awt.Color(204, 153, 0));
        enviat.setFont(new java.awt.Font("Headline R", 0, 12)); // NOI18N
        enviat.setForeground(new java.awt.Color(51, 51, 51));
        enviat.setText("Enviar");
        enviat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviatActionPerformed(evt);
            }
        });
        jPanel1.add(enviat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, 30));

        panelStock.setEditable(false);
        panelStock.setBackground(new java.awt.Color(204, 204, 204));
        panelStock.setColumns(20);
        panelStock.setForeground(new java.awt.Color(0, 0, 0));
        panelStock.setRows(5);
        jScrollPane2.setViewportView(panelStock);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 240, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu = new Menu();
    }//GEN-LAST:event_menuActionPerformed

    private void numAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAlmacenActionPerformed

    private void vproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vproductoActionPerformed

    private void enviatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviatActionPerformed
        // TODO add your handling code here:
        String valmacen = numAlmacen.getText();
        String producto = vproducto.getText().toLowerCase();
        int cantidad1 = (int) vcantidad.getValue();
        if(this.numAlmacen.getText() != null && this.vproducto.getText()!= null){
            int check_almacen = grafo.searchVertice(this.numAlmacen.getText());
            if(check_almacen != -1){
                Nodo<Producto> product = grafo.getVerts()[check_almacen].getProductos().getHead();
                boolean existencia_producto = false;
                for (int i = 0; i < grafo.getVerts()[check_almacen].getProductos().getSize(); i++) {
                    if(this.vproducto.getText().equalsIgnoreCase(product.getData().getNombre())){
                        if (cantidad1 < product.getData().getCantidad()) {
                            existencia_producto = true;
                            product.getData().setCantidad(product.getData().getCantidad() - cantidad1 );
                            JOptionPane.showMessageDialog(null, "El pedido realizado con exito");
                        }
                    }
                product = product.getNext();
                }
                if(!existencia_producto){
                    
                    //PEDIDO
                    
                    for (int i = 0; i < grafo.getNumVerts(); i++) {
                         Nodo<Producto> producto2 = grafo.getVerts()[i].getProductos().getHead();
                        for (int j = 0; j < grafo.getVerts()[i].getProductos().getSize(); j++) {
                            if (producto2.getData().getNombre().equalsIgnoreCase(producto) && cantidad1 < producto2.getData().getCantidad()) {
                                producto2.getData().setCantidad(producto2.getData().getCantidad() - cantidad1 );
                                Dijkstra dijkstra = new Dijkstra(grafo, grafo.getVerts()[i].getNumVertice());
                                dijkstra.caminoMinimos();
                                camino.setText(dijkstra.getCamino(grafo.searchVertice(valmacen)));
                            }
                            producto2 = producto2.getNext();
                        } 
                    }
                    
                    
                }
                Lista bfs = grafo.BFS(grafo, grafo.getVerts()[0].getName());
                this.panelStock.setText(bfs.printProductos());
                this.vproducto.setText("");
                this.numAlmacen.setText("");
                this.vcantidad.setValue(0);
            }else{
                JOptionPane.showMessageDialog(null, "El almacen que ingresaste no existe");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Asegurate de rellenar todas las casillas");
        }
        
    }//GEN-LAST:event_enviatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea camino;
    private javax.swing.JButton enviat;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu;
    private javax.swing.JTextField numAlmacen;
    private javax.swing.JTextArea panelStock;
    private javax.swing.JSpinner vcantidad;
    private javax.swing.JTextField vproducto;
    // End of variables declaration//GEN-END:variables
}
